# Generated by Django 2.2.1 on 2020-03-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_of_files",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Number of Files Uploaded"
                    ),
                ),
                ("username", models.CharField(max_length=80, verbose_name="Username")),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now=True, verbose_name="Uploaded at"),
                ),
            ],
        ),
    ]
