# Generated by Django 2.2.1 on 2020-03-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploader", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_of_files",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Number of Files Uploaded"
                    ),
                ),
                ("username", models.CharField(max_length=80, verbose_name="Username")),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="Created at"),
                ),
            ],
        ),
        migrations.DeleteModel(name="FileUploadCounter",),
    ]
