# Generated by Django 2.2.1 on 2020-03-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploader", "0002_add_fileupload_model"),
    ]

    operations = [
        migrations.RemoveField(model_name="fileupload", name="created_at",),
        migrations.AddField(
            model_name="fileupload",
            name="uploaded_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Uploaded at"),
        ),
    ]
